import type { Metadata } from "next";
import Script from "next/script"; // Import next/script
import "./globals.css";
import { Noto_Sans_Georgian } from "next/font/google";
import Header from "./_components/Header";
import Navigation from "./_components/navigation/Navigation";
import Footer from "./_components/Footer";

export const metadata: Metadata = {
  title: "Chitilebi",
  description: "Generated by create next app",
};

const notoSansGeorgian = Noto_Sans_Georgian({
  weight: ["400", "500", "600", "700", "800"],
  subsets: ["georgian"],
  display: "swap",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ka" className="scroll-smooth">
      <head>
        {/* Google Analytics Script */}
        <Script
          strategy="afterInteractive"
          src="https://www.googletagmanager.com/gtag/js?id=G-ER1V05SFWH"
        />
        <Script
          id="google-analytics"
          strategy="afterInteractive"
          dangerouslySetInnerHTML={{
            __html: 
              window.dataLayer = window.dataLayer || [];
              function gtag(){dataLayer.push(arguments);}
              gtag('js', new Date());
              gtag('config', 'G-ER1V05SFWH', {
                page_path: window.location.pathname,
              });
            ,
          }}
        />
      </head>
      <body
        className={${notoSansGeorgian.className} text-slate-950 overflow-x-hidden}
      >
        <Header />
        <Navigation />
        {children}
        <Footer />
      </body>
    </html>
  );
}